version: '3'

services:

  db:
    restart: always
    image: mysql:8.4.0
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DB=noolingo
      - MYSQL_DSN=mysql://root:secret@tcp(localhost:3306)/noolingo
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./data:/var/lib/mysql

  api-gw:
    build: https://github.com/noolingo/api-gw.git
    ports:
      - "8088:8088"
    environment:
      - NOOLINGO_LISTEN_PORTS_HTTP=8088
      - AUTH_ACCESS_SECRET_KEY=qwerty
      - NOOLINGO_GRPC_CLIENTS_CARDSERVICE=9002
      - NOOLINGO_GRPC_CLIENTS_DECKSERVICE=9003
      - NOOLINGO_GRPC_CLIENTS_STATISTICSERVICE=9004
      - NOOLINGO_GRPC_CLIENTS_USERSERVICE=user-service:8088


  user-service:
    build: https://github.com/noolingo/user-service.git
    ports:
      - "19001:8088"
    depends_on:
      - db
      - api-gw
    environment:
      - AUTH_ACCESS_SECRET_KEY=qwerty
      - AUTH_REFRESH_SECRET_KEY=qwerty
      - USER_SERVICE_MYSQL_DSN=mysql://root:secret@tcp(db:3306)/noolingo
      - USER_SERVICE_PORT=8088

  migration:
    # restart: always
    build: https://github.com/noolingo/migrations.git
    depends_on:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=secret
      - MYSQL_DB=noolingo
      - MYSQL_DSN=mysql://root:secret@tcp(db:3306)/noolingo
    
  swagger:
    build: https://github.com/noolingo/swagger.git
    ports:
      - "8080:8088"
    depends_on:
      - api-gw
    environment:
      - NOOLINGO_LISTEN_PORTS_HTTP=8088
